Migrate to nextjs 13
hansputera/bilibili-dl pull request #3
Opened 2023-05-14 15:01 UTC by Reyuki-san

Changes:
- migrate to app dir
- migrate to tailwindcss
- update nextjs version and its dependencies

2023-05-15 12:05 UTC, Reyuki-san commented
plz riviuw
cc @hanifdwyputras @hansputera

2023-05-18 05:49 UTC, hansputera requested changes
Fix the layout.tsx eslint error, thanks! Line 4

2023-05-18 07:53 UTC, hansputera approved these changes

2023-05-18 10:48 UTC, merged

2023-05-18 10:49 UTC, hansputera commented
LGTM!